### ISSUE TITLE
有用户提交卡2楼bug

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/ROClientPatchCN#1]
有用户提交卡2楼bug

![1 3uqt6 lfz8x0fhze0 vse](https://cloud.githubusercontent.com/assets/28803997/26242253/50107a54-3cba-11e7-99f5-19033e4694b1.jpg)

**Comment by rAthenaCN** [comment]
这个是伊斯鲁得岛学院的左侧房间，地图名称为 iz_ac02 ，在KRO的客户端里这个地图不完整，需要使用到IRO的iz_ac02地图，现在我将这地图加入这个补丁，已正常显示。
![1](https://cloud.githubusercontent.com/assets/19231012/26258274/8cf2c8d2-3cf6-11e7-8cb2-dd5cf399fe05.jpg)
